// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/analyze-image.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/gateway.ts
var GATEWAY = "https://ai.gateway.lovable.dev/v1/chat/completions";
function getApiKey() {
  const key = process.env.LOVABLE_API_KEY;
  if (!key) throw new Error("LOVABLE_API_KEY is not configured");
  return key;
}
var SYSTEM_PROMPTS = {
  analyze: "You are an expert image analyst. Describe the image in detail: subject matter, colors, mood, composition, and notable features. Be thorough but clear.",
  detect: "You are an object detection expert. List every distinct object you can identify in the image. Format as a numbered list with the object name and a brief note about its location/context in the image.",
  ocr: "You are an OCR specialist. Extract ALL text visible in this image. Preserve the original formatting as much as possible. If no text is found, say so.",
  compare: "You are an image comparison expert. Analyze both images and describe their similarities and differences in detail: subject, colors, composition, style, and any notable distinctions.",
  imageToPrompt: "You are a prompt engineer. Generate a single, highly-detailed text-to-image prompt that would recreate this image. Include subject, style, lighting, composition, color palette, mood, camera/lens details if applicable, and quality modifiers. Output ONLY the prompt itself, no preamble or explanation."
};
async function callTextAction(action, imageA, imageB) {
  const apiKey = getApiKey();
  const content = [{ type: "text", text: SYSTEM_PROMPTS[action] }];
  if (imageA) content.push({ type: "image_url", image_url: { url: imageA } });
  if (imageB) content.push({ type: "image_url", image_url: { url: imageB } });
  const resp = await fetch(GATEWAY, {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      model: "google/gemini-3-flash-preview",
      messages: [{ role: "user", content }]
    })
  });
  if (!resp.ok) {
    const t = await resp.text().catch(() => "");
    throw new Error(`AI gateway error ${resp.status}: ${t.slice(0, 200)}`);
  }
  const data = await resp.json();
  return data.choices?.[0]?.message?.content || "No result returned.";
}
var STYLE_MAP = {
  none: "",
  photorealistic: "photorealistic, ultra-detailed, sharp focus, natural lighting",
  cinematic: "cinematic lighting, film grain, dramatic composition, anamorphic look",
  anime: "anime style, vibrant colors, clean line art, cel shading",
  oil_painting: "oil painting on canvas, visible brush strokes, rich color palette",
  watercolor: "watercolor painting, soft edges, flowing pigments, paper texture",
  "3d_render": "3D render, octane render, physically-based materials, soft global illumination",
  pixel_art: "pixel art, 16-bit retro game style, limited palette",
  line_art: "clean line art, black ink on white background, no shading",
  minimalist: "minimalist composition, lots of negative space, simple geometric forms"
};
async function callImageGeneration(opts) {
  const apiKey = getApiKey();
  const styleSuffix = opts.style ? STYLE_MAP[opts.style] || "" : "";
  const aspectSuffix = opts.aspect && opts.aspect !== "1:1" ? `Aspect ratio: ${opts.aspect}.` : "";
  const fullPrompt = [opts.prompt, styleSuffix, aspectSuffix].filter(Boolean).join(" \u2014 ");
  const resp = await fetch(GATEWAY, {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      model: "google/gemini-2.5-flash-image",
      messages: [{ role: "user", content: [{ type: "text", text: fullPrompt }] }],
      modalities: ["image", "text"]
    })
  });
  if (!resp.ok) {
    const t = await resp.text().catch(() => "");
    throw new Error(`AI gateway error ${resp.status}: ${t.slice(0, 200)}`);
  }
  const data = await resp.json();
  const imageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
  const text = data.choices?.[0]?.message?.content || "";
  return { imageUrl, text };
}

// src/lib/mcp/tools/analyze-image.ts
var analyze_image_default = defineTool({
  name: "analyze_image",
  title: "Analyze image",
  description: "Describe an image in detail: subject, colors, mood, composition, notable features.",
  inputSchema: {
    image_url: z.string().url().describe("Public URL of the image to analyze.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ image_url }) => {
    const text = await callTextAction("analyze", image_url);
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/tools/detect-objects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var detect_objects_default = defineTool2({
  name: "detect_objects",
  title: "Detect objects",
  description: "List distinct objects identified in an image with their location/context.",
  inputSchema: {
    image_url: z2.string().url().describe("Public URL of the image.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ image_url }) => {
    const text = await callTextAction("detect", image_url);
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/tools/ocr-image.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var ocr_image_default = defineTool3({
  name: "ocr_image",
  title: "OCR image",
  description: "Extract all visible text from an image, preserving formatting where possible.",
  inputSchema: {
    image_url: z3.string().url().describe("Public URL of the image.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ image_url }) => {
    const text = await callTextAction("ocr", image_url);
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/tools/image-to-prompt.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var image_to_prompt_default = defineTool4({
  name: "image_to_prompt",
  title: "Image to prompt",
  description: "Generate a detailed text-to-image prompt that would recreate the given image.",
  inputSchema: {
    image_url: z4.string().url().describe("Public URL of the image.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ image_url }) => {
    const text = await callTextAction("imageToPrompt", image_url);
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/tools/compare-images.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
var compare_images_default = defineTool5({
  name: "compare_images",
  title: "Compare images",
  description: "Compare two images and describe their similarities and differences.",
  inputSchema: {
    image_url_a: z5.string().url().describe("Public URL of the first image."),
    image_url_b: z5.string().url().describe("Public URL of the second image.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ image_url_a, image_url_b }) => {
    const text = await callTextAction("compare", image_url_a, image_url_b);
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/tools/generate-image.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^3.25.76";
var generate_image_default = defineTool6({
  name: "generate_image",
  title: "Generate image",
  description: "Generate an image from a text prompt. Returns an image data URL.",
  inputSchema: {
    prompt: z6.string().min(1).describe("Text description of the image to generate."),
    style: z6.enum([
      "none",
      "photorealistic",
      "cinematic",
      "anime",
      "oil_painting",
      "watercolor",
      "3d_render",
      "pixel_art",
      "line_art",
      "minimalist"
    ]).optional().describe("Optional artistic style."),
    aspect: z6.enum(["1:1", "16:9", "9:16", "4:3", "3:4"]).optional().describe("Optional aspect ratio.")
  },
  annotations: { readOnlyHint: false, openWorldHint: true },
  handler: async ({ prompt, style, aspect }) => {
    const { imageUrl, text } = await callImageGeneration({ prompt, style, aspect });
    if (imageUrl) {
      return {
        content: [
          { type: "text", text: text || "Image generated." },
          { type: "text", text: `Image data URL: ${imageUrl}` }
        ],
        structuredContent: { image_url: imageUrl }
      };
    }
    return {
      content: [{ type: "text", text: text || "No image generated." }],
      isError: true
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ai-image-toolkit-mcp",
  title: "AI Image Toolkit",
  version: "0.1.0",
  instructions: "Tools for the AI Image Toolkit. Use `analyze_image`, `detect_objects`, `ocr_image`, `image_to_prompt`, or `compare_images` to inspect images by URL. Use `generate_image` to create a new image from a text prompt.",
  tools: [analyze_image_default, detect_objects_default, ocr_image_default, image_to_prompt_default, compare_images_default, generate_image_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
